package ar.edu.utn.frba.domain.enumeracion;

public enum TipoNotificacion {
    DONANTE_SIN_INTERACCION,
    ENTIDAD_DONACION_ASIGNADA,
    DONANTE_DONACION_ASIGNADA,
    ENTIDAD_RUTA_INICIADA,
    DONANTE_RUTA_INICIADA,
    ENTIDAD_ENTREGA_EXITOSA,
    DONANTE_ENTREGA_EXITOSA,
    ENTIDAD_ENTREGA_FALLIDA,
    DONANTE_ENTREGA_FALLIDA,
    DONANTE_MISION_CUMPLIDA,
    DONANTE_CAMBIO_CATEGORIA,
    ALERTA_CLIMATICA
}
